Inputs:
- RawEt
- eta
- phi
- Had
- Em
- HoE

NormalizeInputs: 0
Njets: -1
#Selections: None
Selections: SaturationOnly
#Selections: LeadingJet
#Selections: LeadingJet,RemoveSaturation
#Selections: LeadingJet,RemoveMuons
#Selections: LeadingJet,RemoveMuons,RemoveSaturation
#Selections: RemoveSaturation
KerasModel: dense_model_batchnorm
RegressTo: ratio
#RegressTo: inv_ratio
#RegressTo: pT
#RegressTo: diff
#RegressTo: inv_diff
#Loss: mean_squared_error
Loss: mean_absolute_error
#Loss: mean_absolute_percentage_error
#Loss: mean_squared_logarithmic_error
#Loss: huber_loss
Epochs: 20
